---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 10m
  url: https://helm.mariadb.com/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  chart:
    spec:
      chart: mariadb-operator
      version: "25.8.4"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
  interval: 10m0s
  install:
    remediation:
      retries: 5
  values:
    crds:
      enabled: true
