---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mta
  labels:
    app: mta
spec:
  replicas: 2
  serviceName: mta-headless
  selector:
    matchLabels:
      app: mta
  template:
    metadata:
      labels:
        app: mta
    spec:
      securityContext:
        fsGroup: 101
        runAsUser: 100
        runAsGroup: 101
        runAsNonRoot: true
      containers:
        - name: mta
          image: devture/exim-relay
          command: ["exim", "-bdf", "-q2m"]
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: HOSTNAME
              value: smtp.journalduhacker.net
          ports:
            - name: smtp
              containerPort: 8025
              protocol: TCP
          volumeMounts:
            - name: spool
              mountPath: /var/spool/exim
          livenessProbe:
            tcpSocket:
              port: 8025
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8025
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: spool
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mta-headless
  labels:
    app: mta
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: smtp
      port: 8025
      targetPort: smtp
      protocol: TCP
  selector:
    app: mta
---
apiVersion: v1
kind: Service
metadata:
  name: mta
  labels:
    app: mta
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: 8025
      targetPort: smtp
      protocol: TCP
  selector:
    app: mta
